
services:
  nginx:
    build: ./requirements/nginx
    image: nginx:1337
    container_name: nginx
    depends_on:
      - wordpress
      - adminer
      - redis
    ports:
      - 443:443
    volumes:
      - wordpress_data:/var/www/html
    restart: always
    networks:
      - network

  mariadb:
    build: ./requirements/mariadb
    image: mariadb:1337
    container_name: mariadb
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - network
    restart: always
    env_file:
      - .env

  wordpress:
    build: ./requirements/wordpress
    image: wordpress:1337
    container_name: wordpress
    depends_on:
      - mariadb
    restart: always
    env_file:
      - .env
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - network

#BONUS PART
  redis:
    build: ./requirements/bonus/redis
    image: redis:1337
    container_name: redis
    depends_on:
      - wordpress
    ports:
     - '6379:6379'
    restart: always
    env_file:
      - .env
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - network

  ftp-server:
    build: requirements/bonus/ftp_server
    image: ftp-server:1337
    container_name: ftp-server
    ports:
      - "21:21"
      - "21100-21110:21100-21110"
    volumes:
      - "wordpress_data:/var/www/html"
    networks:
      - network
    restart: always
    environment:
      FTP_USR: ${FTP_USR}
      FTP_PWD: ${FTP_PWD}

  adminer:
    build: ./requirements/bonus/adminer
    image: adminer:1337
    container_name: adminer
    restart: always
    depends_on:
      - mariadb
    expose:
     - "9000"
    networks:
      - network
  website:
    build: ./requirements/bonus/website
    image: website:me
    container_name: website
    restart: always
    ports:
     - "3000:3000"
    networks:
      - network
  cadvisor:
    build: ./requirements/bonus/cAdvisor
    image: cadvisor:1337
    container_name: cadvisor
    ports:
      - "8080:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    networks:
      - network
    restart: always

volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      device: /$HOME/datas/mysql
      o: bind
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      device: /$HOME/datas/wordpress
      o: bind

networks:
  network:
    driver: bridge